export type FrameworkDetail = [kind: string, lede: string, bullets: string[]];

export const FRAMEWORK_DETAIL: Record<string, FrameworkDetail> = {
    'ISO/IEC 42001': ['AI management system',
      'The management-system standard for AI: policy, objectives, roles, risk treatment and continual improvement.',
      ['Annex A controls mapped to platform evidence','Impact assessment templates',
       'Objectives and roles recorded against owners','Internal audit and review trail']],
    'ISO/IEC 27001': ['Information security',
      'Information security management. Where AI systems touch regulated or personal data, these controls still apply.',
      ['Access control evidence for models and agents','Logging and monitoring hooks',
       'Supplier and third-party records','Change control on model versions']],
    'NIST AI RMF': ['Risk framework',
      'A voluntary framework organised around Govern, Map, Measure and Manage.',
      ['Govern — policy set and approval workflow','Map — inventory, ownership and risk tiering',
       'Measure — drift, refusal and adversarial results','Manage — treatment plans and retest']],
    'EU AI Act': ['Regulation',
      'Obligations scale with risk tier. High-risk systems carry documentation, logging, oversight and accuracy duties.',
      ['Risk classification per system','Technical documentation assembled from the register',
       'Automatic event logging retained','Human oversight recorded at decision points']],
    'OWASP LLM Top 10': ['Application risk',
      'The application-security view of LLM systems — the categories the red team tests against.',
      ['Prompt injection probes, direct and indirect','Sensitive information disclosure checks',
       'Excessive agency and tool-abuse cases','Findings scored and retested after fix']],
    'MITRE ATLAS': ['Adversary tactics',
      'A knowledge base of real tactics and techniques used against AI systems.',
      ['Attack simulations mapped to ATLAS techniques','Coverage gaps surfaced per system',
       'Detection hooks routed to your SOC','Recurring schedule, not an annual exercise']]
  };
export const FRAMEWORK_DETAIL_AR: Record<string, FrameworkDetail> = {
    'ISO/IEC 42001': ['نظام إدارة الذكاء الاصطناعي',
      'معيار نظام الإدارة للذكاء الاصطناعي: السياسة والأهداف والأدوار ومعالجة المخاطر والتحسين المستمر.',
      ['ضوابط الملحق A مرتبطة بأدلة المنصة','قوالب تقييم الأثر',
       'الأهداف والأدوار مسجَّلة مقابل المالكين','مسار التدقيق الداخلي والمراجعة']],
    'ISO/IEC 27001': ['أمن المعلومات',
      'إدارة أمن المعلومات. حيث تلامس أنظمة الذكاء الاصطناعي بيانات منظَّمة أو شخصية، تظل هذه الضوابط سارية.',
      ['أدلة التحكم بالوصول للنماذج والوكلاء','آليات التسجيل والمراقبة',
       'سجلّات الموردين والأطراف الثالثة','ضبط التغيير على إصدارات النماذج']],
    'NIST AI RMF': ['إطار المخاطر',
      'إطار طوعي منظَّم حول الحوكمة والتخطيط والقياس والإدارة.',
      ['الحوكمة — مجموعة السياسات ومسار الموافقة','التخطيط — الجرد والملكية وتصنيف المخاطر',
       'القياس — الانحراف والرفض ونتائج الاختبار العدائي','الإدارة — خطط المعالجة وإعادة الاختبار']],
    'EU AI Act': ['التنظيم',
      'تتدرّج الالتزامات حسب مستوى المخاطر. تحمل الأنظمة عالية المخاطر واجبات توثيق وتسجيل ورقابة ودقة.',
      ['تصنيف المخاطر لكل نظام','التوثيق الفني المُجمَّع من السجلّ',
       'تسجيل الأحداث التلقائي المحتفَظ به','الرقابة البشرية المسجَّلة عند نقاط القرار']],
    'OWASP LLM Top 10': ['مخاطر التطبيق',
      'المنظور الأمني التطبيقي لأنظمة النماذج اللغوية الكبيرة — الفئات التي يختبرها الفريق الأحمر.',
      ['اختبارات حقن الطلبات، المباشرة وغير المباشرة','فحوصات إفشاء المعلومات الحسّاسة',
       'حالات الصلاحية المفرطة وإساءة استخدام الأدوات','النتائج مُقيَّمة ومُعاد اختبارها بعد الإصلاح']],
    'MITRE ATLAS': ['تكتيكات الخصم',
      'قاعدة معرفة بالتكتيكات والأساليب الفعلية المستخدَمة ضد أنظمة الذكاء الاصطناعي.',
      ['محاكاة هجمات مرتبطة بأساليب ATLAS','فجوات التغطية مُبرَزة لكل نظام',
       'آليات الكشف موجَّهة إلى مركز العمليات الأمنية لديكم','جدول متكرر، وليس تمرينًا سنويًا']]
  };
